# Generated by Django 6.0 on 2025-12-13 08:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='order_type',
            field=models.CharField(choices=[('market', 'Market Order'), ('limit', 'Limit Order'), ('stop_loss', 'Stop Loss'), ('stop_limit', 'Stop Limit')], default='market', max_length=15),
        ),
        migrations.AddField(
            model_name='trade',
            name='stop_loss_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('cancelled', 'Cancelled'), ('partial', 'Partially Filled'), ('stop_loss_triggered', 'Stop Loss Triggered')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='StopLossOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stop_price', models.DecimalField(decimal_places=2, help_text='Price at which to trigger the stop loss', max_digits=10)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Limit price for stop-limit orders', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('triggered', 'Triggered'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.stock')),
                ('triggered_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.trade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_loss_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
