# Generated by Django 6.0 on 2025-12-13 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_trade_order_type_trade_stop_loss_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sma_20', models.DecimalField(blank=True, decimal_places=4, help_text='20-day Simple Moving Average', max_digits=10, null=True)),
                ('sma_50', models.DecimalField(blank=True, decimal_places=4, help_text='50-day Simple Moving Average', max_digits=10, null=True)),
                ('sma_200', models.DecimalField(blank=True, decimal_places=4, help_text='200-day Simple Moving Average', max_digits=10, null=True)),
                ('ema_12', models.DecimalField(blank=True, decimal_places=4, help_text='12-day Exponential Moving Average', max_digits=10, null=True)),
                ('ema_26', models.DecimalField(blank=True, decimal_places=4, help_text='26-day Exponential Moving Average', max_digits=10, null=True)),
                ('macd_line', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('macd_signal', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('macd_histogram', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rsi_14', models.DecimalField(blank=True, decimal_places=2, help_text='14-day RSI', max_digits=5, null=True)),
                ('bb_upper', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('bb_middle', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('bb_lower', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('bb_width', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('trend_direction', models.CharField(choices=[('strong_bullish', 'Strong Bullish'), ('bullish', 'Bullish'), ('neutral', 'Neutral'), ('bearish', 'Bearish'), ('strong_bearish', 'Strong Bearish')], default='neutral', max_length=20)),
                ('trend_strength', models.DecimalField(blank=True, decimal_places=2, help_text='Trend strength 0-100', max_digits=5, null=True)),
                ('price_vs_sma20', models.DecimalField(blank=True, decimal_places=2, help_text='% above/below SMA20', max_digits=5, null=True)),
                ('price_vs_sma50', models.DecimalField(blank=True, decimal_places=2, help_text='% above/below SMA50', max_digits=5, null=True)),
                ('price_vs_sma200', models.DecimalField(blank=True, decimal_places=2, help_text='% above/below SMA200', max_digits=5, null=True)),
                ('support_level', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('resistance_level', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('volume_sma_20', models.BigIntegerField(blank=True, help_text='20-day average volume', null=True)),
                ('volume_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Current volume vs average', max_digits=5, null=True)),
                ('overall_signal', models.CharField(choices=[('strong_buy', 'Strong Buy'), ('buy', 'Buy'), ('hold', 'Hold'), ('sell', 'Sell'), ('strong_sell', 'Strong Sell')], default='hold', max_length=15)),
                ('signal_strength', models.DecimalField(blank=True, decimal_places=2, help_text='Signal confidence 0-100', max_digits=5, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_indicators', to='trading.stock')),
            ],
            options={
                'verbose_name': 'Technical Indicators',
                'verbose_name_plural': 'Technical Indicators',
            },
        ),
    ]
