# Generated by Django 6.0 on 2025-12-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_technicalindicators'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(help_text='Exchange name (e.g., NYSE, NASDAQ, PSE)', max_length=50, unique=True)),
                ('timezone', models.CharField(default='America/New_York', help_text='Exchange timezone', max_length=50)),
                ('market_open', models.TimeField(help_text='Market opening time')),
                ('market_close', models.TimeField(help_text='Market closing time')),
                ('premarket_open', models.TimeField(blank=True, help_text='Pre-market opening time', null=True)),
                ('premarket_close', models.TimeField(blank=True, help_text='Pre-market closing time', null=True)),
                ('afterhours_open', models.TimeField(blank=True, help_text='After-hours opening time', null=True)),
                ('afterhours_close', models.TimeField(blank=True, help_text='After-hours closing time', null=True)),
                ('monday_trading', models.BooleanField(default=True)),
                ('tuesday_trading', models.BooleanField(default=True)),
                ('wednesday_trading', models.BooleanField(default=True)),
                ('thursday_trading', models.BooleanField(default=True)),
                ('friday_trading', models.BooleanField(default=True)),
                ('saturday_trading', models.BooleanField(default=False)),
                ('sunday_trading', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trading Hours',
                'verbose_name_plural': 'Trading Hours',
                'ordering': ['exchange'],
            },
        ),
        migrations.CreateModel(
            name='MarketHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(help_text='Exchange name', max_length=50)),
                ('name', models.CharField(help_text='Holiday name', max_length=100)),
                ('date', models.DateField(help_text='Holiday date')),
                ('is_partial_day', models.BooleanField(default=False, help_text='Half-day trading')),
                ('early_close_time', models.TimeField(blank=True, help_text='Early closing time for partial days', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('exchange', 'date')},
            },
        ),
    ]
