# Generated by Django 6.0 on 2025-12-13 12:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_tradinghours_marketholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('basics', 'Trading Basics'), ('technical', 'Technical Analysis'), ('fundamental', 'Fundamental Analysis'), ('risk_management', 'Risk Management'), ('psychology', 'Trading Psychology'), ('strategies', 'Trading Strategies'), ('market_types', 'Market Types')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('content', models.TextField(help_text='Lesson content in markdown format')),
                ('key_concepts', models.JSONField(default=list, help_text='List of key concepts covered')),
                ('estimated_read_time', models.IntegerField(help_text='Estimated reading time in minutes')),
                ('order_index', models.IntegerField(default=0, help_text='Order within category')),
                ('recommended_practice', models.TextField(blank=True, help_text='Recommended practice exercises')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='trading.tradinglesson')),
            ],
            options={
                'ordering': ['category', 'order_index'],
                'unique_together': {('category', 'order_index')},
            },
        ),
        migrations.CreateModel(
            name='TradingPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_fees_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of winning trades', max_digits=5)),
                ('average_win', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('average_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('profit_factor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross profit / Gross loss', max_digits=8)),
                ('best_trade_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('worst_trade_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('average_holding_period_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('most_traded_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('favorite_trading_time', models.CharField(blank=True, max_length=20, null=True)),
                ('estimated_skill_level', models.CharField(choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='novice', max_length=20)),
                ('trading_days_active', models.IntegerField(default=0)),
                ('longest_winning_streak', models.IntegerField(default=0)),
                ('longest_losing_streak', models.IntegerField(default=0)),
                ('largest_position_size', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('risk_per_trade_avg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average % of account risked per trade', max_digits=5)),
                ('stop_loss_usage_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% of trades with stop loss', max_digits=5)),
                ('simulation_start_date', models.DateTimeField(auto_now_add=True)),
                ('last_trade_date', models.DateTimeField(blank=True, null=True)),
                ('peak_account_value', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=12)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trading Performance',
                'verbose_name_plural': 'Trading Performance',
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('quiz_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.tradinglesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
