# Generated by Django 6.0 on 2025-12-14 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_tradinglesson_tradingperformance_userlessonprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalindicators',
            name='ema_200',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='200-day Exponential Moving Average', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='technicalindicators',
            name='ema_200_direction',
            field=models.CharField(blank=True, choices=[('up', 'Upward'), ('down', 'Downward'), ('sideways', 'Sideways')], help_text='200 EMA trend direction', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='technicalindicators',
            name='sma_200_direction',
            field=models.CharField(blank=True, choices=[('up', 'Upward'), ('down', 'Downward'), ('sideways', 'Sideways')], help_text='200 SMA trend direction', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='PullbackAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField()),
                ('daily_trend', models.CharField(max_length=20)),
                ('price_vs_sma20', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sma20_slope', models.CharField(help_text='rising/falling/flat', max_length=10)),
                ('volume_trend', models.CharField(max_length=20)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_from_high', models.DecimalField(decimal_places=2, help_text='% from recent high', max_digits=5)),
                ('is_pullback_valid', models.BooleanField(default=False)),
                ('hourly_support_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hourly_resistance_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rsi_1h', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('volume_spike', models.BooleanField(default=False)),
                ('five_min_momentum', models.CharField(max_length=20)),
                ('entry_signal_strength', models.IntegerField(default=0, help_text='0-10 signal strength')),
                ('action_recommended', models.CharField(max_length=30)),
                ('confidence_level', models.IntegerField(default=0, help_text='0-100 confidence')),
                ('risk_assessment', models.CharField(max_length=20)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.stock')),
            ],
            options={
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='PullbackStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_timeframe', models.CharField(default='daily', help_text='Timeframe for trend analysis', max_length=20)),
                ('entry_timeframe', models.CharField(default='1hour', help_text='Timeframe for entry signals', max_length=20)),
                ('risk_per_trade', models.DecimalField(decimal_places=2, default=0.5, help_text='Risk percentage per trade', max_digits=5)),
                ('max_trades_per_day', models.IntegerField(default=1, help_text='Maximum trades allowed per day')),
                ('pullback_percentage', models.DecimalField(decimal_places=2, default=2.0, help_text='Minimum pullback % from high', max_digits=5)),
                ('sma_period', models.IntegerField(default=20, help_text='SMA period for trend confirmation')),
                ('volume_confirmation', models.BooleanField(default=True, help_text='Require volume confirmation')),
                ('stop_loss_atr_multiple', models.DecimalField(decimal_places=2, default=2.0, help_text='Stop loss as ATR multiple', max_digits=5)),
                ('take_profit_ratio', models.DecimalField(decimal_places=2, default=2.0, help_text='Risk:Reward ratio', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pullback_strategies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PullbackTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_date', models.DateTimeField()),
                ('trend_direction', models.CharField(default='bullish', max_length=20)),
                ('pullback_high', models.DecimalField(decimal_places=2, help_text='High before pullback', max_digits=10)),
                ('pullback_low', models.DecimalField(decimal_places=2, help_text='Low of pullback', max_digits=10)),
                ('pullback_percentage_actual', models.DecimalField(decimal_places=2, help_text='Actual pullback %', max_digits=5)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('entry_reason', models.CharField(blank=True, choices=[('pullback_bounce', 'Pullback Bounce off SMA'), ('volume_confirmation', 'Volume Confirmation'), ('hammer_candle', 'Hammer Candle Pattern'), ('support_bounce', 'Support Level Bounce'), ('oversold_bounce', 'Oversold RSI Bounce')], max_length=30, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('stop_loss_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('take_profit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exit_date', models.DateTimeField(blank=True, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pnl_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('setup', 'Setup Identified'), ('waiting_entry', 'Waiting for Entry'), ('entered', 'Position Entered'), ('stop_hit', 'Stop Loss Hit'), ('target_hit', 'Take Profit Hit'), ('manual_exit', 'Manual Exit'), ('expired', 'Setup Expired')], default='setup', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.stock')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.pullbackstrategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-setup_date'],
            },
        ),
        migrations.CreateModel(
            name='TradingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('trade', 'Trade'), ('analysis', 'Analysis'), ('signal', 'Signal')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('stock_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('trade_id', models.IntegerField(blank=True, null=True)),
                ('price_data', models.JSONField(blank=True, help_text='JSON data for prices, indicators, etc.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyTradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trades_taken', models.IntegerField(default=0)),
                ('max_trades_allowed', models.IntegerField(default=1)),
                ('total_risk_taken', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('market_condition', models.CharField(blank=True, max_length=30, null=True)),
                ('aapl_daily_range', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('volume_vs_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pre_market_analysis', models.TextField(blank=True, null=True)),
                ('post_session_review', models.TextField(blank=True, null=True)),
                ('lessons_learned', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
