# Generated by Django 6.0 on 2025-12-15 03:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_technicalindicators_ema_200_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreMarketStopLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('stop_loss', 'Stop Loss'), ('trailing_stop', 'Trailing Stop'), ('stop_limit', 'Stop Limit')], default='stop_loss', max_length=15)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stop_price', models.DecimalField(decimal_places=2, help_text='Price at which to trigger the stop loss', max_digits=10)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Limit price for stop-limit orders', max_digits=10, null=True)),
                ('trail_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed dollar amount for trailing stop', max_digits=10, null=True)),
                ('trail_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage for trailing stop', max_digits=5, null=True)),
                ('trigger_condition', models.CharField(choices=[('market_open', 'Trigger at Market Open'), ('pre_market', 'Trigger in Pre-Market'), ('any_session', 'Trigger Any Trading Session')], default='market_open', max_length=15)),
                ('good_till_cancelled', models.BooleanField(default=True, help_text='Order remains active until cancelled')),
                ('expiry_date', models.DateField(blank=True, help_text='Order expires after this date', null=True)),
                ('execute_in_premarket', models.BooleanField(default=False, help_text='Allow execution in pre-market hours')),
                ('execute_in_afterhours', models.BooleanField(default=False, help_text='Allow execution in after-hours')),
                ('max_slippage_percent', models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='Maximum acceptable slippage percentage', max_digits=5)),
                ('min_volume_threshold', models.IntegerField(default=1000, help_text='Minimum volume required for execution')),
                ('status', models.CharField(choices=[('pending', 'Pending Market Open'), ('active', 'Active'), ('triggered', 'Triggered'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, help_text='When order became active', null=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('executed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('executed_quantity', models.IntegerField(blank=True, null=True)),
                ('slippage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('execution_session', models.CharField(blank=True, help_text='pre-market, regular, after-hours', max_length=20, null=True)),
                ('strategy_name', models.CharField(blank=True, help_text='Trading strategy this order is part of', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('alert_settings', models.JSONField(default=dict, help_text='Email/SMS alert preferences')),
                ('parent_order', models.ForeignKey(blank=True, help_text='For linked orders like OCO', null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.premarketstoploss')),
                ('related_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.trade')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premarket_stop_losses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pre-Market Stop Loss',
                'verbose_name_plural': 'Pre-Market Stop Losses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreMarketWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_premarket', models.BooleanField(default=True, help_text='Monitor during pre-market hours')),
                ('premarket_alert_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Alert if price moves this % in pre-market', max_digits=5, null=True)),
                ('auto_create_stop_loss', models.BooleanField(default=False, help_text='Auto-create stop loss at market open')),
                ('default_stop_loss_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Default stop loss percentage below entry', max_digits=5, null=True)),
                ('target_entry_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('planned_position_size', models.IntegerField(blank=True, help_text='Planned number of shares', null=True)),
                ('max_daily_loss', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum acceptable loss for this stock today', max_digits=10, null=True)),
                ('risk_reward_ratio', models.DecimalField(decimal_places=2, default=Decimal('2.0'), help_text='Target risk:reward ratio', max_digits=5)),
                ('trade_premarket', models.BooleanField(default=False)),
                ('trade_regular_hours', models.BooleanField(default=True)),
                ('trade_afterhours', models.BooleanField(default=False)),
                ('email_alerts', models.BooleanField(default=True)),
                ('sms_alerts', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premarket_watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pre-Market Watchlist',
                'verbose_name_plural': 'Pre-Market Watchlists',
                'ordering': ['stock__symbol'],
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
