# Generated by Django 6.0 on 2025-12-15 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_premarketstoploss_premarketwatchlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path_type', models.CharField(choices=[('beginner_complete', 'Complete Beginner Program'), ('day_trader', 'Day Trading Mastery'), ('swing_trader', 'Swing Trading Expert'), ('options_trader', 'Options Trading Specialist'), ('technical_analyst', 'Technical Analysis Master'), ('risk_manager', 'Risk Management Expert'), ('portfolio_manager', 'Portfolio Management Pro')], max_length=30)),
                ('description', models.TextField()),
                ('estimated_duration_weeks', models.IntegerField(help_text='Estimated completion time')),
                ('difficulty_progression', models.CharField(default='Beginner to Advanced', max_length=50)),
                ('prerequisite_skills', models.JSONField(default=list, help_text='Required starting skills')),
                ('target_skills', models.JSONField(default=list, help_text='Skills developed upon completion')),
                ('completion_certificate', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['path_type'],
            },
        ),
        migrations.CreateModel(
            name='PracticeModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('module_type', models.CharField(choices=[('simulation', 'Trading Simulation'), ('quiz', 'Knowledge Quiz'), ('case_study', 'Case Study Analysis'), ('pattern_recognition', 'Chart Pattern Recognition'), ('risk_calculator', 'Risk Management Calculator'), ('backtesting', 'Strategy Backtesting'), ('market_replay', 'Historical Market Replay'), ('options_strategy', 'Options Strategy Builder')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=15)),
                ('required_level', models.IntegerField(default=1, help_text='Minimum skill level required')),
                ('estimated_duration', models.IntegerField(help_text='Duration in minutes')),
                ('max_attempts', models.IntegerField(default=3, help_text='Maximum attempts allowed')),
                ('passing_score', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('content_data', models.JSONField(help_text='Module configuration and content')),
                ('scoring_rules', models.JSONField(help_text='How performance is scored')),
                ('completion_count', models.IntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TradingChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('challenge_type', models.CharField(choices=[('weekly_performance', 'Weekly Performance Challenge'), ('risk_management', 'Risk Management Challenge'), ('pattern_trading', 'Pattern Recognition Challenge'), ('sector_rotation', 'Sector Rotation Challenge'), ('earnings_play', 'Earnings Season Challenge'), ('volatility_trading', 'Volatility Trading Challenge'), ('paper_trading', 'Paper Trading Competition')], max_length=30)),
                ('duration', models.CharField(choices=[('daily', 'Daily Challenge'), ('weekly', 'Weekly Challenge'), ('monthly', 'Monthly Challenge'), ('quarterly', 'Quarterly Challenge')], max_length=15)),
                ('description', models.TextField()),
                ('rules', models.JSONField(help_text='Challenge rules and constraints')),
                ('success_criteria', models.JSONField(help_text='What constitutes success')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField()),
                ('max_participants', models.IntegerField(default=100)),
                ('entry_requirements', models.JSONField(default=dict, help_text='Skill level or other requirements')),
                ('prizes', models.JSONField(default=list, help_text='Prizes for top performers')),
                ('skill_points_reward', models.IntegerField(default=0, help_text='Skill points for participation')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PathLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.tradinglesson')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.learningpath')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('path', 'order_index')},
            },
        ),
        migrations.AddField(
            model_name='learningpath',
            name='lessons',
            field=models.ManyToManyField(related_name='learning_paths', through='trading.PathLesson', to='trading.tradinglesson'),
        ),
        migrations.CreateModel(
            name='PathPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField()),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.learningpath')),
                ('unlock_after_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.tradinglesson')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.practicemodule')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='learningpath',
            name='practice_modules',
            field=models.ManyToManyField(related_name='learning_paths', through='trading.PathPractice', to='trading.practicemodule'),
        ),
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('technical_analysis', 'Technical Analysis'), ('fundamental_analysis', 'Fundamental Analysis'), ('risk_management', 'Risk Management'), ('market_psychology', 'Market Psychology'), ('position_sizing', 'Position Sizing'), ('entry_timing', 'Entry Timing'), ('exit_strategy', 'Exit Strategy'), ('portfolio_management', 'Portfolio Management'), ('options_trading', 'Options Trading'), ('sector_analysis', 'Sector Analysis')], max_length=30)),
                ('current_level', models.IntegerField(choices=[(0, 'No Experience'), (1, 'Novice (0-3 months)'), (2, 'Beginner (3-6 months)'), (3, 'Developing (6-12 months)'), (4, 'Intermediate (1-2 years)'), (5, 'Competent (2-3 years)'), (6, 'Proficient (3-5 years)'), (7, 'Advanced (5+ years)'), (8, 'Expert (Professional level)'), (9, 'Master (Teaching level)')], default=0)),
                ('target_level', models.IntegerField(choices=[(0, 'No Experience'), (1, 'Novice (0-3 months)'), (2, 'Beginner (3-6 months)'), (3, 'Developing (6-12 months)'), (4, 'Intermediate (1-2 years)'), (5, 'Competent (2-3 years)'), (6, 'Proficient (3-5 years)'), (7, 'Advanced (5+ years)'), (8, 'Expert (Professional level)'), (9, 'Master (Teaching level)')], default=4)),
                ('knowledge_score', models.DecimalField(decimal_places=2, default=0, help_text='Theoretical knowledge', max_digits=5)),
                ('practical_score', models.DecimalField(decimal_places=2, default=0, help_text='Practical application', max_digits=5)),
                ('consistency_score', models.DecimalField(decimal_places=2, default=0, help_text='Consistent application', max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, help_text='Weighted average', max_digits=5)),
                ('confidence_rating', models.DecimalField(decimal_places=1, default=0, help_text='Self-assessed confidence 0-10', max_digits=3)),
                ('last_assessment_date', models.DateTimeField(auto_now=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('improvement_rate', models.DecimalField(decimal_places=2, default=0, help_text='Points gained per month', max_digits=5)),
                ('recommended_practice_hours_weekly', models.IntegerField(default=5)),
                ('focus_areas', models.JSONField(default=list, help_text='Specific areas to focus on')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-overall_score'],
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.AddField(
            model_name='practicemodule',
            name='target_skills',
            field=models.ManyToManyField(blank=True, related_name='practice_modules', to='trading.skillassessment'),
        ),
        migrations.CreateModel(
            name='SkillBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('knowledge', 'Knowledge Mastery'), ('performance', 'Trading Performance'), ('consistency', 'Consistency Achievement'), ('risk_management', 'Risk Management'), ('learning', 'Learning Progress'), ('community', 'Community Contribution'), ('challenge', 'Challenge Achievement')], max_length=20)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], max_length=10)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(help_text='Requirements to earn this badge')),
                ('icon_url', models.CharField(blank=True, max_length=200)),
                ('skill_points', models.IntegerField(default=0, help_text='Skill points awarded')),
                ('unlocks', models.JSONField(default=list, help_text='What this badge unlocks')),
                ('total_earned', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'tier'],
                'unique_together': {('name', 'tier')},
            },
        ),
        migrations.CreateModel(
            name='UserPracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('failed', 'Failed')], default='started', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('speed_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('answers', models.JSONField(default=dict, help_text='User answers and choices')),
                ('performance_data', models.JSONField(default=dict, help_text='Detailed performance metrics')),
                ('strengths_identified', models.JSONField(default=list)),
                ('weaknesses_identified', models.JSONField(default=list)),
                ('recommended_focus', models.TextField(blank=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='trading.practicemodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('active', 'Active'), ('completed', 'Completed'), ('disqualified', 'Disqualified'), ('withdrawn', 'Withdrawn')], default='registered', max_length=15)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_rank', models.IntegerField(blank=True, null=True)),
                ('performance_data', models.JSONField(default=dict, help_text='Detailed performance tracking')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_rank', models.IntegerField(blank=True, null=True)),
                ('achieved_goals', models.JSONField(default=list, help_text='Goals achieved during challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='trading.tradingchallenge')),
            ],
            options={
                'ordering': ['-final_score'],
                'unique_together': {('user', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress_data', models.JSONField(default=dict, help_text='Progress data when badge was earned')),
                ('is_displayed', models.BooleanField(default=True, help_text='Show on profile')),
                ('display_order', models.IntegerField(default=0)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='trading.skillbadge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserLearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_lesson_index', models.IntegerField(default=0)),
                ('current_practice_index', models.IntegerField(default=0)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_grade', models.CharField(blank=True, max_length=3)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('practices_completed', models.IntegerField(default=0)),
                ('average_practice_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.learningpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'path')},
            },
        ),
    ]
